type Dictionary<T> = {[key: string]: T}

const emojis: Dictionary<string> = {
	achievement: '🏅',
	add: '➕',
	applicantsAvailable: '📬',
	applicantsEmpty: '📭',
	chat: '💭',
	close: '🛑',
	collector: '🧳',
	construction: '🏗',
	countdown: '⏲',
	currency: '📎',
	employmentTermination: '🔫',
	hobby: '💚',
	income: '📈',
	language: '🏳️‍🌈',
	magnet: '🧲',
	mall: '🏬',
	noPerson: '🕳',
	opening: '🎈',
	person: '👤',
	purchasing: '🛒',
	recruitment: '👏',
	retirement: '👻',
	seat: '💺',
	selling: '🤝',
	shop: '🏪',
	shopProductsEmpty: '🥺',
	skill: '⚗️',
	skillFinished: '✅',
	stats: '📊',
	storage: '📦',
	underConstruction: '🚧',
	warning: '⚠️',
	wikidataItem: 'ℹ️',
	yes: '👍'
}

export default emojis
